language: java
jdk:
- openjdk8
- oraclejdk8
- oraclejdk9
script: ./gradlew build compileMinJosmVersion
deploy:
  - provider: releases
    api-key:
      secure: GUDz8pgKvi5M6m4oCMJoKqKT3GjU42PYTF97ASRaPjxVTXH0kETdmV0zADZuzITo5X5uALozP3pRjrtnnDFMmyyo+KIhhNplKr7T5aLJQMwI+bLT+ioseRlxqxAHPILf9qZKKbJKEsKAOEQ8N8fDxI5oyivXICT15LLjrCVS6Z8=
    skip_cleanup: true
    file:
      - build/dist/fieldpapers.jar
      - build/tmp/jar/MANIFEST.MF
    on:
      tags: true
      jdk: openjdk8
      repo: fieldpapers/josm-fieldpapers

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9
