language: java
jdk:
- openjdk8
- oraclejdk8
- oraclejdk9
script: ./gradlew build compileMinJosmVersion
deploy:
  - provider: releases
    api-key:
      secure: GUDz8pgKvi5M6m4oCMJoKqKT3GjU42PYTF97ASRaPjxVTXH0kETdmV0zADZuzITo5X5uALozP3pRjrtnnDFMmyyo+KIhhNplKr7T5aLJQMwI+bLT+ioseRlxqxAHPILf9qZKKbJKEsKAOEQ8N8fDxI5oyivXICT15LLjrCVS6Z8=
    skip_cleanup: true
    file:
      - build/dist/fieldpapers.jar
      - build/tmp/jar/MANIFEST.MF
    on:
      tags: true
      jdk: openjdk8
      repo: fieldpapers/josm-fieldpapers

jobs:
  include:
    - stage: i18n
      language: python
      python: "3.5"
      install: pip install git+https://github.com/transifex/transifex-client.git@a706ba0cb910e66e852010bcd742221363c7e8be#egg=transifex-client
      script: |
        if [ ! -z "$TRANSIFEX_TOKEN" ]; then
          ./gradlew generatePot
          tx --token="$TRANSIFEX_TOKEN" --force-save --no-interactive init
          git checkout HEAD .tx/config
          tx push -s --no-interactive
        fi

stages:
  - test
  - name: i18n
    if: type = push AND branch = master

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9
  - language: python
