language: java
jdk:
- openjdk8
- oraclejdk8
- oraclejdk9
script: ./gradlew build compileMinJosmVersion && cp -T `find build/libs/*.jar | head -1` "build/libs/fieldpapers.jar"
deploy:
  provider: releases
  api_key:
    secure: PutYourEncryptedApiKeyHere
  file: "build/libs/fieldpapers.jar"
  on:
    tags: true
    jdk: openjdk8
    repo: iandees/josm-fieldpapers

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9
